UPDATE public.matches
SET flag_home = CASE team_home
    WHEN 'África do Sul' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Africa%20do%20Sul.png'
    WHEN 'Alemanha' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Alemanha.png'
    WHEN 'Arábia Saudita' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Arabia%20Saudita.png'
    WHEN 'Argélia' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Argelia.png'
    WHEN 'Argentina' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Argentina.png'
    WHEN 'Austrália' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Australia.png'
    WHEN 'Áustria' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Austria.png'
    WHEN 'Bélgica' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Belgica.png'
    WHEN 'Bósnia e Herzegovina' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Bosnia.png'
    WHEN 'Brasil' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Brasil.png'
    WHEN 'Cabo Verde' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Cabo%20Verde.png'
    WHEN 'Canadá' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Canada.png'
    WHEN 'Catar' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Catar.png'
    WHEN 'Colômbia' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Colombia.png'
    WHEN 'Coreia do Sul' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Coreia%20do%20Sul.png'
    WHEN 'Costa do Marfim' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Costa%20do%20Marfim.png'
    WHEN 'Croácia' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Croacia.png'
    WHEN 'Curaçao' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Curacao.png'
    WHEN 'Egito' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Egito.png'
    WHEN 'Equador' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Equador.png'
    WHEN 'Escócia' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Escocia.png'
    WHEN 'Espanha' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Espanha.png'
    WHEN 'Estados Unidos' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Estados%20Unidos.png'
    WHEN 'França' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Franca.png'
    WHEN 'Gana' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Gana.png'
    WHEN 'Haiti' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Haiti.png'
    WHEN 'Inglaterra' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Inglaterra.png'
    WHEN 'Irã' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Ira.png'
    WHEN 'Iraque' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Iraque.png'
    WHEN 'Japão' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Japao.png'
    WHEN 'Jordânia' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Jordania.png'
    WHEN 'Marrocos' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Marrocos.png'
    WHEN 'México' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Mexico.png'
    WHEN 'Noruega' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Noruega.png'
    WHEN 'Nova Zelândia' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Nova%20Zelandia.png'
    WHEN 'Países Baixos' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Paises%20Baixos.png'
    WHEN 'Panamá' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Panama.png'
    WHEN 'Paraguai' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Paraguai.png'
    WHEN 'Portugal' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Portugal.png'
    WHEN 'República Democrática do Congo' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Congo.png'
    WHEN 'República Tcheca' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Republica%20Tcheca.png'
    WHEN 'Senegal' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Senegal.png'
    WHEN 'Suécia' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Suecia.png'
    WHEN 'Suíça' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Suica.png'
    WHEN 'Tunísia' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Tunisia.png'
    WHEN 'Turquia' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Turquia.png'
    WHEN 'Uruguai' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Uruguai.png'
    WHEN 'Uzbequistão' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Uzbequistao.png'
    ELSE flag_home
END,
flag_away = CASE team_away
    WHEN 'África do Sul' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Africa%20do%20Sul.png'
    WHEN 'Alemanha' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Alemanha.png'
    WHEN 'Arábia Saudita' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Arabia%20Saudita.png'
    WHEN 'Argélia' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Argelia.png'
    WHEN 'Argentina' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Argentina.png'
    WHEN 'Austrália' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Australia.png'
    WHEN 'Áustria' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Austria.png'
    WHEN 'Bélgica' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Belgica.png'
    WHEN 'Bósnia e Herzegovina' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Bosnia.png'
    WHEN 'Brasil' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Brasil.png'
    WHEN 'Cabo Verde' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Cabo%20Verde.png'
    WHEN 'Canadá' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Canada.png'
    WHEN 'Catar' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Catar.png'
    WHEN 'Colômbia' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Colombia.png'
    WHEN 'Coreia do Sul' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Coreia%20do%20Sul.png'
    WHEN 'Costa do Marfim' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Costa%20do%20Marfim.png'
    WHEN 'Croácia' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Croacia.png'
    WHEN 'Curaçao' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Curacao.png'
    WHEN 'Egito' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Egito.png'
    WHEN 'Equador' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Equador.png'
    WHEN 'Escócia' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Escocia.png'
    WHEN 'Espanha' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Espanha.png'
    WHEN 'Estados Unidos' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Estados%20Unidos.png'
    WHEN 'França' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Franca.png'
    WHEN 'Gana' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Gana.png'
    WHEN 'Haiti' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Haiti.png'
    WHEN 'Inglaterra' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Inglaterra.png'
    WHEN 'Irã' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Ira.png'
    WHEN 'Iraque' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Iraque.png'
    WHEN 'Japão' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Japao.png'
    WHEN 'Jordânia' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Jordania.png'
    WHEN 'Marrocos' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Marrocos.png'
    WHEN 'México' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Mexico.png'
    WHEN 'Noruega' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Noruega.png'
    WHEN 'Nova Zelândia' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Nova%20Zelandia.png'
    WHEN 'Países Baixos' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Paises%20Baixos.png'
    WHEN 'Panamá' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Panama.png'
    WHEN 'Paraguai' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Paraguai.png'
    WHEN 'Portugal' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Portugal.png'
    WHEN 'República Democrática do Congo' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Congo.png'
    WHEN 'República Tcheca' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Republica%20Tcheca.png'
    WHEN 'Senegal' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Senegal.png'
    WHEN 'Suécia' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Suecia.png'
    WHEN 'Suíça' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Suica.png'
    WHEN 'Tunísia' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Tunisia.png'
    WHEN 'Turquia' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Turquia.png'
    WHEN 'Uruguai' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Uruguai.png'
    WHEN 'Uzbequistão' THEN 'https://avjcjgsosfewukkdsgri.supabase.co/storage/v1/object/public/Bandeiras/Uzbequistao.png'
    ELSE flag_away
END;
